# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: ghcr.io/nouhaylafth/flask-app:latest  # Change l'image ici avec ton propre registre
        ports:
        - containerPort: 8080
