# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: docker.io/nouhaylafth/flask-app:latest

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        export KUBECONFIG=$HOME/.kube/config
        
    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Send Google Chat notification on success
      if: success()
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"text": "Pipeline succeeded! Deployed version: '"${GITHUB_SHA}"'"}' \
        ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

    - name: Send Google Chat notification on failure
      if: failure()
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"text": "Pipeline failed! Commit: '"${GITHUB_SHA}"'"}' \
        ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
